package com.alura.anotaai.ui.theme

import androidx.compose.ui.graphics.Color

// Modern Professional Palette - Deep Indigo & Slate
val primaryLight = Color(0xFF4F52B2)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDDE0FF)
val onPrimaryContainerLight = Color(0xFF00006E)
val secondaryLight = Color(0xFF5B5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE0E1F9)
val onSecondaryContainerLight = Color(0xFF181A2C)
val tertiaryLight = Color(0xFF77536D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD7F1)
val onTertiaryContainerLight = Color(0xFF2D1228)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDFBFF)
val onBackgroundLight = Color(0xFF1B1B1F)
val surfaceLight = Color(0xFFFDFBFF)
val onSurfaceLight = Color(0xFF1B1B1F)
val surfaceVariantLight = Color(0xFFE3E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF767680)

val primaryDark = Color(0xFFB9BBFF)
val onPrimaryDark = Color(0xFF1D1F83)
val primaryContainerDark = Color(0xFF363999)
val onPrimaryContainerDark = Color(0xFFDDE0FF)
val secondaryDark = Color(0xFFC3C5DD)
val onSecondaryDark = Color(0xFF2D2F42)
val secondaryContainerDark = Color(0xFF434659)
val onSecondaryContainerDark = Color(0xFFE0E1F9)
val tertiaryDark = Color(0xFFE5B9D7)
val onTertiaryDark = Color(0xFF45263D)
val tertiaryContainerDark = Color(0xFF5D3C54)
val onTertiaryContainerDark = Color(0xFFFFD7F1)
val backgroundDark = Color(0xFF1B1B1F)
val onBackgroundDark = Color(0xFFE3E1E6)
val surfaceDark = Color(0xFF1B1B1F)
val onSurfaceDark = Color(0xFFE3E1E6)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF90909A)
